[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 4
include_trailing_comma = true
known_first_party = ["generate-wavs"]

[tool.black]
line-length = 79
target-version = ["py313"]
preview = true
skip-string-normalization = true
